export const config = {
  itemsCountPerPage: 10,
  dbHost: 'host',
  dbPort: 1234,
  dbDatabase: 'db_name',
  dbUsername: 'db_username',
  dbPassword: 'db_password',
  dbSynchronize: false,
  dbLogging: false,
  jwtSecret: '',
  jwtTimeToExpire: '0s',
  jwtCookieTimeToExpire: 0,
  jwtCookieDomain: 'host',
  mailHost: 'host',
  mailPort: 1234,
  mailUsername: 'mail_username',
  mailPassword: 'mail_password',
  mailFrom: 'no-replay@exaple.com',
};
